language: node_js
node_js:
  - "4.1"
  - "4.0"
env:
  - CXX=g++-4.8
services:
  - redis-server
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
# uncomment this line if your project needs to run something other than `rake`:
before_script:
  - npm install -g gulp
script: gulp travis
